version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Projector.dockerfile
    ports:
      - 9999:9999
    volumes:
      - root_data:/root
    tty: true

volumes:
  root_data:
    driver: local